artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1cvIiXwgPgCW3Kvf1YyQZ9-RMH_uXbYgj/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

missing_value_handling:
  root_dir: artifacts/missing_value_handling
  input_data_dir: artifacts/data_ingestion  # Path to ingested data
  processed_data_dir: artifacts/missing_value_handling/processed_data # Path to save processed data
  categorical_imputation:
    no_imputation_features: # Features imputed with 'No'
      - Alley
      - Fence
      - MasVnrType
      - FireplaceQu
      - GarageCond
      - GarageType
      - GarageFinish
      - GarageQual
      - BsmtCond
      - BsmtExposure
      - BsmtQual
    unf_imputation_features: # Features imputed with 'Unf'
      - BsmtFinType1
      - BsmtFinType2
    most_frequent_imputation_features: # Features imputed with most frequent category
      - Electrical
  numerical_imputation:
    zero_imputation_features: # Features imputed with 0
      - MasVnrArea
      - LotFrontage
    year_built_imputation_feature: # Feature imputed with 'YearBuilt'
      - GarageYrBlt
    general_numerical_mean_imputation: True # Flag for general numerical mean imputation later

outlier_handling: # New section for outlier handling
  root_dir: artifacts/outlier_handling
  input_data_dir: artifacts/missing_value_handling/processed_data # Input from missing value handling
  processed_data_dir: artifacts/outlier_handling/processed_data # Output directory
  outlier_ids: # List of outlier IDs to remove
    - 598
    - 955
    - 935
    - 1299
    - 250
    - 314
    - 336
    - 707
    - 379
    - 1183
    - 692
    - 186
    - 441
    - 186
    - 524
    - 739
    - 636
    - 1062
    - 1191
    - 496
    - 198
    - 1338